server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: accounts
  data:
    mongodb:
      uri: mongodb://mongo:27017/accounts
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      accounts-customer: accounts.customer.change
    consumer:
      group-id: accounts
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
---
server:
  port: 8080
logging:
  level:
    root: INFO
spring:
  config:
    activate:
      on-profile: gke
